#!/usr/bin/env bash

LATEX="latexmk"

CLEAN="$LATEX -C"
C_FLAGS="-shell-escape -pdf"

$CLEAN
$LATEX $C_FLAGS main.tex

pdf_viewer="$1"

if [ -z "$pdf_viewer" ]; then
  echo "resume: no pdf viewer provided"
  exit 1
fi

if ! (which "$pdf_viewer" &> /dev/null); then
  echo "resume: $pdf_viewer: No such file or directory"
  exit 1
fi

$pdf_viewer main.pdf 
